<Project>

  <!-- https://github.com/dotnet/sdk/issues/22515 -->
  <ItemGroup>
    <None Remove="*.csproj.DotSettings" />
  </ItemGroup>

  <Target Name="NormalizeAtomUICitySourceRepositoryUrl"
          AfterTargets="SourceControlManagerPublishTranslatedUrls"
          BeforeTargets="InitializeSourceControlInformation"
          Condition="'$(RepositoryUrl)' != ''">
    <PropertyGroup>
      <PrivateRepositoryUrl>$(RepositoryUrl)</PrivateRepositoryUrl>
      <ScmRepositoryUrl>$(RepositoryUrl)</ScmRepositoryUrl>
    </PropertyGroup>
    <ItemGroup>
      <SourceRoot Update="@(SourceRoot)"
                  RepositoryUrl="$(RepositoryUrl)"
                  ScmRepositoryUrl="$(RepositoryUrl)" />
    </ItemGroup>
  </Target>

</Project>
