using System.Text;
using AtomUI.City.Generators.EventBus;

namespace AtomUI.City.Generators.DependencyInjection;

internal static class ServiceRegistrarSourceBuilder
{
    public static string GetRegistrarTypeName(string assemblyName)
    {
        var identifier = new StringBuilder();
        foreach (var character in assemblyName)
        {
            identifier.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (identifier.Length == 0 || char.IsDigit(identifier[0]))
        {
            identifier.Insert(0, '_');
        }

        return $"AtomUI.City.Generated.GeneratedServiceRegistrar_{identifier}_{ComputeHash(assemblyName):X8}";
    }

    public static string Build(
        string assemblyName,
        string? ownerModuleTypeName,
        IReadOnlyList<ServiceRegistrationMetadata> registrations,
        IReadOnlyList<string> referencedRegistrarTypeNames,
        EventGenerationManifest? eventManifest = null)
    {
        var typeName = GetRegistrarTypeName(assemblyName);
        var separator = typeName.LastIndexOf('.');
        var ns = typeName.Substring(0, separator);
        var name = typeName.Substring(separator + 1);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS1591 // Generated registrar is compiler infrastructure.");
        builder.Append("[assembly: global::AtomUI.City.Core.DependencyInjection.GeneratedServiceManifestAttribute(typeof(global::")
            .Append(typeName).AppendLine("))]");
        if (eventManifest is { IsEmpty: false })
        {
            builder.Append("[assembly: global::AtomUI.City.EventBus.GeneratedEventManifestAttribute(typeof(global::")
                .Append(typeName).AppendLine("), global::AtomUI.City.EventBus.GeneratedEventManifestAttribute.CurrentVersion)]");
        }
        builder.AppendLine();
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();
        builder.Append("public sealed class ").Append(name)
            .AppendLine(" : global::AtomUI.City.Core.DependencyInjection.IServiceRegistrar");
        builder.AppendLine("{");

        for (var index = 0; index < registrations.Count; index++)
        {
            if (registrations[index].ExposedServiceTypeNames.Count > 1)
            {
                builder.Append("    private static readonly object BackingKey")
                    .Append(index).AppendLine(" = new object();");
            }
        }

        builder.AppendLine("    public void Register(global::AtomUI.City.Core.DependencyInjection.IServiceRegistrarContext context)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");

        foreach (var referencedRegistrar in referencedRegistrarTypeNames.Distinct(StringComparer.Ordinal).OrderBy(value => value, StringComparer.Ordinal))
        {
            builder.Append("        context.RegisterRegistrar(typeof(global::").Append(referencedRegistrar)
                .Append("), static () => new global::").Append(referencedRegistrar).AppendLine("());");
        }

        if (registrations.Count > 0 && ownerModuleTypeName is not null)
        {
            builder.Append("        context.Register(typeof(global::").Append(ownerModuleTypeName)
                .AppendLine("), static services =>");
            builder.AppendLine("        {");

            for (var index = 0; index < registrations.Count; index++)
            {
                AppendRegistration(builder, registrations[index], index);
            }

            builder.AppendLine("        });");
        }

        if (eventManifest is { IsEmpty: false })
        {
            foreach (var ownerGroup in eventManifest.Contracts.Select(value => value.OwnerTypeName)
                         .Concat(eventManifest.Handlers.Select(value => value.OwnerTypeName))
                         .Distinct(StringComparer.Ordinal).OrderBy(value => value, StringComparer.Ordinal))
            {
                builder.Append("        context.Register(typeof(global::").Append(ownerGroup).AppendLine("), static services =>");
                builder.AppendLine("        {");
                foreach (var contract in eventManifest.Contracts.Where(value => value.OwnerTypeName == ownerGroup)
                             .OrderBy(value => value.ContractId, StringComparer.Ordinal))
                {
                    builder.Append("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(global::AtomUI.City.EventBus.EventContractDescriptor.GeneratedShared<global::")
                        .Append(contract.EventTypeName).Append(">(new global::AtomUI.City.EventBus.EventContractId(")
                        .Append(ToLiteral(contract.ContractId)).Append("), typeof(global::").Append(contract.EventTypeName)
                        .Append(").Assembly, ").Append(contract.SchemaVersion).Append(", ")
                        .Append(ToLiteral(contract.SchemaFingerprint)).AppendLine(")));");
                    foreach (var channel in contract.Channels.OrderBy(value => value.Name, StringComparer.Ordinal))
                    {
                        builder.Append("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(global::AtomUI.City.EventBus.EventChannelDescriptor.Create(new global::AtomUI.City.EventBus.EventChannel<global::")
                            .Append(contract.EventTypeName).Append(">(").Append(ToLiteral(channel.Name)).AppendLine("), new global::AtomUI.City.EventBus.EventChannelOptions");
                        builder.AppendLine("            {");
                        builder.Append("                Capacity = ").Append(channel.Capacity).AppendLine(",");
                        builder.Append("                BackpressurePolicy = (global::AtomUI.City.EventBus.EventChannelBackpressurePolicy)").Append(channel.BackpressurePolicy).AppendLine(",");
                        builder.Append("                ExecutionMode = (global::AtomUI.City.EventBus.EventChannelExecutionMode)").Append(channel.ExecutionMode).AppendLine(",");
                        builder.Append("                MaximumConcurrency = ").Append(channel.MaximumConcurrency).AppendLine(",");
                        if (channel.QueueWaitTimeoutMilliseconds > 0)
                            builder.Append("                QueueWaitTimeout = global::System.TimeSpan.FromMilliseconds(").Append(channel.QueueWaitTimeoutMilliseconds).AppendLine("),");
                        builder.AppendLine("            })));");
                    }
                }

                foreach (var handler in eventManifest.Handlers.Where(value => value.OwnerTypeName == ownerGroup)
                             .OrderBy(value => value.HandlerTypeName, StringComparer.Ordinal))
                {
                    builder.Append("            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::")
                        .Append(handler.HandlerTypeName).Append(">(services, static provider => new global::")
                        .Append(handler.HandlerTypeName).Append('(');
                    for (var index = 0; index < handler.ConstructorParameterTypeNames.Count; index++)
                    {
                        if (index > 0) builder.Append(", ");
                        builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::")
                            .Append(handler.ConstructorParameterTypeNames[index]).Append(">(provider)");
                    }
                    builder.AppendLine("));");
                    builder.Append("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(global::AtomUI.City.EventBus.GeneratedEventHandlerDescriptor.Create<global::")
                        .Append(handler.EventTypeName).Append(", global::").Append(handler.HandlerTypeName).Append(">(typeof(global::")
                        .Append(handler.OwnerTypeName).Append("), ").Append(ToLiteral(handler.ChannelName))
                        .Append(", (global::AtomUI.City.EventBus.EventDispatchPolicy)").Append(handler.DispatchPolicy)
                        .Append(", (global::AtomUI.City.EventBus.EventDispatchMode)").Append(handler.DispatchMode)
                        .Append(", (global::AtomUI.City.EventBus.EventErrorPolicy)").Append(handler.ErrorPolicy)
                        .Append(", ").Append(handler.HandlerTimeoutMilliseconds)
                        .Append(", ").Append(handler.DisableAfterFailures).AppendLine(")));");
                }

                builder.AppendLine("        });");
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static void Apply(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor, bool replace, bool tryAdd)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (replace) global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(services, descriptor);");
        builder.AppendLine("        else if (tryAdd) global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, descriptor);");
        builder.AppendLine("        else");
        builder.AppendLine("        {");
        builder.AppendLine("            foreach (var existing in services)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (existing.ServiceType == descriptor.ServiceType && existing.IsKeyedService == descriptor.IsKeyedService && (!descriptor.IsKeyedService || global::System.Object.Equals(existing.ServiceKey, descriptor.ServiceKey)))");
        builder.AppendLine("                    throw new global::System.InvalidOperationException($\"Generated service '{descriptor.ServiceType.FullName}' has already been registered for the same key. Use Replace or TryAdd to declare the conflict policy.\");");
        builder.AppendLine("            }");
        builder.AppendLine("            services.Add(descriptor);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendRegistration(StringBuilder builder, ServiceRegistrationMetadata registration, int index)
    {
        var lifetime = "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime." + registration.Lifetime;
        var implementation = "typeof(global::" + registration.ImplementationTypeName + ")";

        if (registration.ExposedServiceTypeNames.Count == 1)
        {
            AppendDescriptor(builder, registration, registration.ExposedServiceTypeNames[0], implementation, lifetime, null);
            return;
        }

        builder.Append("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.DescribeKeyed(")
            .Append(implementation).Append(", BackingKey").Append(index).Append(", ")
            .Append(implementation).Append(", ").Append(lifetime).AppendLine("));");

        foreach (var exposed in registration.ExposedServiceTypeNames)
        {
            AppendDescriptor(builder, registration, exposed, implementation, lifetime, index);
        }
    }

    private static void AppendDescriptor(StringBuilder builder, ServiceRegistrationMetadata registration, string exposed, string implementation, string lifetime, int? backingIndex)
    {
        builder.Append("            Apply(services, ");
        if (backingIndex is null)
        {
            if (registration.Key is null)
            {
                builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof(global::")
                    .Append(exposed).Append("), ").Append(implementation).Append(", ").Append(lifetime).Append(')');
            }
            else
            {
                builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.DescribeKeyed(typeof(global::")
                    .Append(exposed).Append("), ").Append(ToLiteral(registration.Key)).Append(", ")
                    .Append(implementation).Append(", ").Append(lifetime).Append(')');
            }
        }
        else if (registration.Key is null)
        {
            builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof(global::")
                .Append(exposed).Append("), static provider => global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<global::")
                .Append(registration.ImplementationTypeName).Append(">(provider, BackingKey").Append(backingIndex.Value)
                .Append("), ").Append(lifetime).Append(')');
        }
        else
        {
            builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.DescribeKeyed(typeof(global::")
                .Append(exposed).Append("), ").Append(ToLiteral(registration.Key))
                .Append(", static (provider, _) => global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<global::")
                .Append(registration.ImplementationTypeName).Append(">(provider, BackingKey").Append(backingIndex.Value)
                .Append("), ").Append(lifetime).Append(')');
        }

        builder.Append(", ").Append(registration.Replace ? "true" : "false")
            .Append(", ").Append(registration.TryAdd ? "true" : "false").AppendLine(");");
    }

    private static string ToLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";

    private static uint ComputeHash(string value)
    {
        var hash = 2166136261u;
        foreach (var character in value)
        {
            hash ^= character;
            hash *= 16777619;
        }
        return hash;
    }
}
