using System.Text;
using AtomUI.City.Generators.Common;

namespace AtomUI.City.Generators.Presentation;

internal static class PresentationViewRegistrarSourceBuilder
{
    public static string Build(PresentationViewManifest manifest)
    {
        if (manifest is null)
        {
            throw new ArgumentNullException(nameof(manifest));
        }

        var typeName = GeneratedCodeNames.CreateRegistrarTypeName(GeneratorFeature.Presentation, "ViewRegistrar");
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.Append("namespace ").Append(typeName.Namespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("public static class ").Append(typeName.Name).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    public static void RegisterViews(global::AtomUI.City.Presentation.IViewRegistry registry)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(registry);");

        foreach (var view in manifest.Views)
        {
            AppendViewRegistration(builder, view);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void AppendViewRegistration(
        StringBuilder builder,
        PresentationViewManifestEntry view)
    {
        builder.AppendLine();
        builder.AppendLine("        registry.Register(");
        builder.AppendLine("            new global::AtomUI.City.Presentation.ViewDescriptor(");
        builder.Append("                typeof(").Append(ToGlobalTypeName(view.ViewModelTypeName)).AppendLine("),");
        builder.Append("                typeof(").Append(ToGlobalTypeName(view.ViewTypeName)).AppendLine("),");
        builder.Append("                viewKey: ").Append(ToStringLiteral(view.ViewKey)).AppendLine(",");
        AppendViewFactory(builder, view);
        builder.Append("                pluginId: ").Append(ToStringLiteral(view.PluginId)).AppendLine(",");
        builder.Append("                contributionId: ").Append(ToStringLiteral(view.ContributionId));
        AppendConstructorParameterTypes(builder, view);
    }

    private static void AppendViewFactory(
        StringBuilder builder,
        PresentationViewManifestEntry view)
    {
        builder
            .Append("                static context => new ")
            .Append(ToGlobalTypeName(view.ViewTypeName));

        if (view.ConstructorParameters.Count == 0)
        {
            builder.AppendLine("(),");
            return;
        }

        builder.AppendLine("(");

        for (var index = 0; index < view.ConstructorParameters.Count; index++)
        {
            var parameter = view.ConstructorParameters[index];
            builder
                .Append("                    ")
                .Append(ToRequiredServiceExpression(parameter.TypeName));

            builder.AppendLine(index == view.ConstructorParameters.Count - 1 ? string.Empty : ",");
        }

        builder.AppendLine("                ),");
    }

    private static void AppendConstructorParameterTypes(
        StringBuilder builder,
        PresentationViewManifestEntry view)
    {
        if (view.ConstructorParameters.Count == 0)
        {
            builder.AppendLine("));");
            return;
        }

        builder.AppendLine(",");
        builder.Append("                constructorParameterTypes: [");

        for (var index = 0; index < view.ConstructorParameters.Count; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append("typeof(")
                .Append(ToGlobalTypeName(view.ConstructorParameters[index].TypeName))
                .Append(")");
        }

        builder.AppendLine("]));");
    }

    private static string ToRequiredServiceExpression(string typeName)
    {
        var globalTypeName = ToGlobalTypeName(typeName);

        return $"({globalTypeName})(context.Services.GetService(typeof({globalTypeName})) ?? throw new global::System.InvalidOperationException({ToStringLiteral($"Required service '{typeName}' was not registered.")}))";
    }

    private static string ToGlobalTypeName(string typeName)
    {
        return "global::" + typeName;
    }

    private static string ToStringLiteral(string? value)
    {
        return value is null ? "null" : "@\"" + value.Replace("\"", "\"\"") + "\"";
    }
}
