using System.Text;

namespace AtomUI.City.Generators.Modularity;

internal static class ModuleRegistrarSourceBuilder
{
    public static string GetRegistrarTypeName(string assemblyName)
    {
        if (string.IsNullOrWhiteSpace(assemblyName))
        {
            throw new ArgumentException("Assembly name cannot be empty.", nameof(assemblyName));
        }

        var identifier = new StringBuilder(assemblyName.Length);

        foreach (var character in assemblyName)
        {
            identifier.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (identifier.Length == 0 || char.IsDigit(identifier[0]))
        {
            identifier.Insert(0, '_');
        }

        return $"AtomUI.City.Generated.GeneratedModularityModuleRegistrar_{identifier}_{ComputeHash(assemblyName):X8}";
    }

    public static string Build(
        string assemblyName,
        IReadOnlyList<ModuleMetadata> modules,
        IReadOnlyList<string> referencedRegistrarTypeNames)
    {
        if (string.IsNullOrWhiteSpace(assemblyName))
        {
            throw new ArgumentException("Assembly name cannot be empty.", nameof(assemblyName));
        }

        if (modules is null)
        {
            throw new ArgumentNullException(nameof(modules));
        }

        if (referencedRegistrarTypeNames is null)
        {
            throw new ArgumentNullException(nameof(referencedRegistrarTypeNames));
        }

        var registrarTypeName = GetRegistrarTypeName(assemblyName);
        var lastSeparator = registrarTypeName.LastIndexOf('.');
        var registrarNamespace = registrarTypeName.Substring(0, lastSeparator);
        var registrarName = registrarTypeName.Substring(lastSeparator + 1);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS1591 // Generated registrar is compiler infrastructure.");
        builder.Append("[assembly: global::AtomUI.City.Core.Modularity.GeneratedModuleManifestAttribute(typeof(global::")
            .Append(registrarTypeName)
            .AppendLine("))]");
        builder.AppendLine();
        builder.Append("namespace ").Append(registrarNamespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("public sealed class ").Append(registrarName)
            .AppendLine(" : global::AtomUI.City.Core.Modularity.IModuleRegistrar");
        builder.AppendLine("{");
        builder.AppendLine("    public void Register(global::AtomUI.City.Core.Modularity.IModuleRegistrarContext context)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");

        foreach (var referencedRegistrar in referencedRegistrarTypeNames
                     .Distinct(StringComparer.Ordinal)
                     .OrderBy(name => name, StringComparer.Ordinal))
        {
            builder.Append("        new global::").Append(referencedRegistrar)
                .AppendLine("().Register(context);");
        }

        foreach (var module in modules)
        {
            AppendModuleRegistration(builder, module);
        }

        foreach (var root in modules.Where(module => module.IsApplicationRoot))
        {
            builder.Append("        context.AddApplicationRoot(typeof(global::")
                .Append(root.TypeName)
                .AppendLine("));");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void AppendModuleRegistration(StringBuilder builder, ModuleMetadata module)
    {
        builder.AppendLine();
        builder.AppendLine("        context.Register(");
        builder.AppendLine("            new global::AtomUI.City.Core.Modularity.ModuleDescriptor(");
        builder.Append("                ").Append(ToStringLiteral(module.Name)).AppendLine(",");
        builder.Append("                typeof(global::").Append(module.TypeName).AppendLine("),");
        builder.Append("                ").Append(ToStringLiteral(module.Version)).AppendLine(",");
        builder.Append("                ").Append(ToStringLiteral(module.Description)).AppendLine(",");

        if (module.Dependencies.Count == 0)
        {
            builder.AppendLine("                []),");
        }
        else
        {
            builder.AppendLine("                [");

            for (var index = 0; index < module.Dependencies.Count; index++)
            {
                var dependency = module.Dependencies[index];
                builder.Append("                    new global::AtomUI.City.Core.Modularity.ModuleDependencyDescriptor(typeof(global::")
                    .Append(dependency.TypeName)
                    .Append("), ")
                    .Append(dependency.Optional ? "true" : "false")
                    .AppendLine(index == module.Dependencies.Count - 1 ? ")" : "),");
            }

            builder.AppendLine("                ]),");
        }

        builder.Append("            static () => new global::")
            .Append(module.TypeName)
            .AppendLine("());");
    }

    private static string ToStringLiteral(string? value)
    {
        return value is null ? "null" : "@\"" + value.Replace("\"", "\"\"") + "\"";
    }

    private static uint ComputeHash(string value)
    {
        const uint offset = 2166136261;
        const uint prime = 16777619;
        var hash = offset;

        foreach (var character in value)
        {
            hash ^= character;
            hash *= prime;
        }

        return hash;
    }
}
