using System.Text;
using AtomUI.City.Generators.Common;
using Microsoft.CodeAnalysis.CSharp;

namespace AtomUI.City.Generators.Routing;

internal static class RouteSourceBuilder
{
    public static string Build(
        IReadOnlyList<RouteMapMetadata> routeMaps,
        RouteManifest manifest)
    {
        if (routeMaps is null)
        {
            throw new ArgumentNullException(nameof(routeMaps));
        }

        if (manifest is null)
        {
            throw new ArgumentNullException(nameof(manifest));
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS1591 // Generated route API is documented by its route declarations.");

        foreach (var routeMap in routeMaps.OrderBy(map => map.TypeName, StringComparer.Ordinal))
        {
            AppendRouteMap(builder, routeMap);
        }

        AppendManifest(builder, manifest);
        return builder.ToString().Replace("\r\n", "\n").Replace('\r', '\n');
    }

    private static void AppendRouteMap(StringBuilder builder, RouteMapMetadata routeMap)
    {
        var separator = routeMap.TypeName.LastIndexOf('.');
        var namespaceName = separator < 0 ? null : routeMap.TypeName.Substring(0, separator);
        var typeName = separator < 0 ? routeMap.TypeName : routeMap.TypeName.Substring(separator + 1);

        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine();
            builder.AppendLine("{");
        }

        var indent = namespaceName is null ? string.Empty : "    ";
        builder.Append(indent).Append("public static partial class ").Append(typeName).AppendLine();
        builder.Append(indent).AppendLine("{");

        foreach (var route in routeMap.Routes.OrderBy(route => route.MethodName, StringComparer.Ordinal))
        {
            AppendRouteMethod(builder, route, indent + "    ");
        }

        builder.Append(indent).AppendLine("}");
        if (namespaceName is not null)
        {
            builder.AppendLine("}");
        }

        builder.AppendLine();
    }

    private static void AppendRouteMethod(
        StringBuilder builder,
        RouteDefinitionMetadata route,
        string indent)
    {
        var returnType = route.RouteReferenceTypeName ?? "AtomUI.City.Routing.RouteReference";
        builder.Append(indent)
            .Append("public static partial global::")
            .Append(returnType)
            .Append(' ')
            .Append(EscapeIdentifier(route.MethodName))
            .Append("() => ");

        if (route.ParameterTypeName is null)
        {
            var referenceId = route.Kind == RouteDefinitionMetadataKind.ExtensionPoint
                ? route.ExtensionPoint
                : route.Id;
            builder.Append("new global::")
                .Append(returnType)
                .Append('(')
                .Append(ToStringLiteral(referenceId))
                .AppendLine(");");
            return;
        }

        builder.Append("new global::AtomUI.City.Routing.RouteReference<global::")
            .Append(route.ParameterTypeName)
            .Append(">(")
            .Append(ToStringLiteral(route.Id));

        if (route.ParameterBindings.Count == 0)
        {
            builder.AppendLine(");");
            return;
        }

        builder.AppendLine(", static parameters =>");
        builder.Append(indent).AppendLine("    new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.OrdinalIgnoreCase)");
        builder.Append(indent).AppendLine("    {");
        foreach (var binding in route.ParameterBindings)
        {
            builder.Append(indent).Append("        [")
                .Append(ToStringLiteral(binding.RouteName))
                .Append("] = global::System.Convert.ToString(parameters.")
                .Append(EscapeIdentifier(binding.MemberName))
                .Append(", global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty,")
                .AppendLine();
        }

        builder.Append(indent).AppendLine("    });");
    }

    private static void AppendManifest(StringBuilder builder, RouteManifest manifest)
    {
        var generatedType = GeneratedCodeNames.CreateRegistrarTypeName(GeneratorFeature.Routing, "RouteManifest");
        builder.Append("namespace ").Append(generatedType.Namespace).AppendLine();
        builder.AppendLine("{");
        builder.Append("    public static class ").Append(generatedType.Name).AppendLine();
        builder.AppendLine("    {");
        builder.AppendLine("        public static global::AtomUI.City.Routing.RouteGraphSnapshot CreateSnapshot(long version = 1)");
        builder.AppendLine("        {");
        builder.AppendLine("            return global::AtomUI.City.Routing.RouteGraphSnapshot.Create(CreateDescriptors(), version);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.City.Routing.RouteDescriptor> CreateDescriptors()");
        builder.AppendLine("        {");
        builder.AppendLine("            return new global::AtomUI.City.Routing.RouteDescriptor[]");
        builder.AppendLine("            {");

        foreach (var route in manifest.Routes)
        {
            AppendDescriptor(builder, route);
        }

        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void AppendDescriptor(StringBuilder builder, RouteManifestRoute route)
    {
        builder.AppendLine("                new global::AtomUI.City.Routing.RouteDescriptor(");
        builder.Append("                    ").Append(ToStringLiteral(route.Id)).AppendLine(",");
        builder.Append("                    global::AtomUI.City.Routing.RouteDefinitionKind.").Append(route.Kind).AppendLine(",");
        builder.Append("                    ").Append(ToStringLiteral(route.Template)).AppendLine(",");

        if (route.ViewModelTypeName is null)
        {
            builder.AppendLine("                    viewModelTarget: null,");
        }
        else
        {
            builder.AppendLine("                    new global::AtomUI.City.Routing.ViewModelTargetDescriptor(");
            builder.Append("                        typeof(global::").Append(route.ViewModelTypeName).AppendLine("),");
            AppendStringArray(builder, "parameterBindings", route.ParameterBindingNames, 24);
            builder.Append("                        reuseKey: ").Append(ToStringLiteral(route.ReuseKey)).AppendLine(",");
            builder.Append("                        activationHint: ").Append(ToStringLiteral(route.ActivationHint)).AppendLine("),");
        }

        builder.Append("                    parentRouteId: ").Append(ToStringLiteral(route.ParentRouteId)).AppendLine(",");
        builder.Append("                    outletName: ").Append(ToStringLiteral(route.OutletName)).AppendLine(",");
        builder.Append("                    extensionPoint: ").Append(ToStringLiteral(route.ExtensionPoint)).AppendLine(",");
        builder.Append("                    redirectTargetRouteId: ").Append(ToStringLiteral(route.RedirectTargetRouteId)).AppendLine(",");
        AppendTypeArray(builder, "enterGuardTypes", route.EnterGuardTypeNames);
        AppendTypeArray(builder, "leaveGuardTypes", route.LeaveGuardTypeNames);
        AppendTypeArray(builder, "matchPolicyTypes", route.MatchPolicyTypeNames);
        builder.AppendLine("                    metadata: new global::AtomUI.City.Routing.RouteMetadataDescriptor(");
        builder.Append("                        titleKey: ").Append(ToStringLiteral(route.TitleKey)).AppendLine(",");
        builder.Append("                        descriptionKey: ").Append(ToStringLiteral(route.DescriptionKey)).AppendLine(",");
        builder.Append("                        breadcrumbKey: ").Append(ToStringLiteral(route.BreadcrumbKey)).AppendLine(",");
        builder.Append("                        groupKey: ").Append(ToStringLiteral(route.GroupKey)).AppendLine(",");
        builder.Append("                        errorTitleKey: ").Append(ToStringLiteral(route.ErrorTitleKey)).AppendLine("),");
        builder.AppendLine("                    contributionId: null,");
        AppendTypeArray(builder, "resolverTypes", route.ResolverTypeNames);
        AppendTypeArray(builder, "middlewareTypes", route.MiddlewareTypeNames, isLast: true);
        builder.AppendLine("                ),");
    }

    private static void AppendTypeArray(
        StringBuilder builder,
        string parameterName,
        IReadOnlyList<string> typeNames,
        bool isLast = false)
    {
        builder.Append("                    ").Append(parameterName).Append(": ");
        if (typeNames.Count == 0)
        {
            builder.Append("null");
        }
        else
        {
            builder.Append("new global::System.Type[] { ")
                .Append(string.Join(", ", typeNames.Select(type => "typeof(global::" + type + ")")))
                .Append(" }");
        }

        builder.AppendLine(isLast ? string.Empty : ",");
    }

    private static void AppendStringArray(
        StringBuilder builder,
        string parameterName,
        IReadOnlyList<string> values,
        int indentation)
    {
        builder.Append(' ', indentation).Append(parameterName).Append(": ");
        if (values.Count == 0)
        {
            builder.AppendLine("null,");
            return;
        }

        builder.Append("new string[] { ")
            .Append(string.Join(", ", values.Select(ToStringLiteral)))
            .AppendLine(" },");
    }

    private static string ToStringLiteral(string? value)
    {
        return value is null ? "null" : "@\"" + value.Replace("\"", "\"\"") + "\"";
    }

    private static string EscapeIdentifier(string identifier)
    {
        if (identifier.StartsWith("@", StringComparison.Ordinal))
        {
            return identifier;
        }

        return SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ||
            SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None
                ? "@" + identifier
                : identifier;
    }
}
