using System.Text;

namespace AtomUI.City.Generators.Data;

internal static class DataClientRegistrarSourceBuilder
{
    public static string GetRegistrarTypeName(string assemblyName)
    {
        if (string.IsNullOrWhiteSpace(assemblyName))
        {
            throw new ArgumentException("Assembly name cannot be empty.", nameof(assemblyName));
        }
        var identifier = new string(assemblyName.Select(static character =>
            char.IsLetterOrDigit(character) || character == '_' ? character : '_').ToArray());
        return $"AtomUI.City.Generated.GeneratedDataClientRegistrar_{identifier}_{ComputeHash(assemblyName):X8}";
    }

    public static string Build(string assemblyName, IReadOnlyList<DataClientGenerationMetadata> clients)
    {
        if (string.IsNullOrWhiteSpace(assemblyName))
        {
            throw new ArgumentException("Assembly name cannot be empty.", nameof(assemblyName));
        }

        if (clients is null)
        {
            throw new ArgumentNullException(nameof(clients));
        }
        var fullName = GetRegistrarTypeName(assemblyName);
        var separator = fullName.LastIndexOf('.');
        var ns = fullName.Substring(0, separator);
        var name = fullName.Substring(separator + 1);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS1591 // Generated registrar is compiler infrastructure.");
        builder.Append("[assembly: global::AtomUI.City.Data.GeneratedDataClientManifestAttribute(typeof(global::")
            .Append(fullName)
            .AppendLine("), global::AtomUI.City.Data.GeneratedDataClientManifestAttribute.CurrentVersion)]");
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.Append("public sealed class ").Append(name)
            .AppendLine(" : global::AtomUI.City.Data.IDataClientDescriptorRegistrar");
        builder.AppendLine("{");
        builder.AppendLine("    public void Register(global::AtomUI.City.Data.DataClientDescriptorCatalog catalog)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(catalog);");

        foreach (var client in clients.OrderBy(static client => client.ClientId, StringComparer.Ordinal))
        {
            builder.AppendLine("        catalog.Register(new global::AtomUI.City.Data.DataClientDescriptor(");
            builder.Append("            ").Append(Literal(client.ClientId)).AppendLine(",");
            builder.Append("            typeof(").Append(TypeReference(client.TypeName)).AppendLine("),");
            builder.Append("            (global::AtomUI.City.Data.DataTransportKind)").Append(client.TransportKind).AppendLine(",");
            builder.Append("            ").Append(Literal(client.Version)).AppendLine(",");
            builder.AppendLine("            new global::AtomUI.City.Data.DataOperationDescriptor[]");
            builder.AppendLine("            {");
            foreach (var operation in client.Operations.OrderBy(static operation => operation.OperationName, StringComparer.Ordinal))
            {
                builder.AppendLine("                new global::AtomUI.City.Data.DataOperationDescriptor(");
                builder.Append("                    ").Append(Literal(operation.OperationName)).AppendLine(",");
                builder.Append("                    typeof(").Append(TypeReference(operation.RequestTypeName)).AppendLine("),");
                builder.Append("                    typeof(").Append(TypeReference(operation.ResponseTypeName)).AppendLine("),");
                builder.Append("                    (global::AtomUI.City.Data.DataAccessMode)").Append(operation.AccessMode).AppendLine(",");
                builder.Append("                    (global::AtomUI.City.Data.DataConcurrencyPolicy)").Append(operation.ConcurrencyPolicy).AppendLine(",");
                builder.Append("                    ").Append(operation.TimeoutMilliseconds > 0
                    ? $"global::System.TimeSpan.FromMilliseconds({operation.TimeoutMilliseconds})"
                    : "null").AppendLine(",");
                builder.Append("                    ").Append(operation.MaxRetryAttempts).AppendLine(",");
                builder.Append("                    ").Append(operation.CacheEnabled ? "true" : "false").AppendLine(",");
                builder.Append("                    ").Append(Literal(operation.AuthenticationPolicy)).AppendLine("),");
            }

            builder.AppendLine("            }));");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString().Replace("\r\n", "\n").Replace('\r', '\n');
    }

    private static string Literal(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";

    private static string TypeReference(string typeName)
    {
        if (typeName.StartsWith("global::", StringComparison.Ordinal)
            || typeName.StartsWith("(", StringComparison.Ordinal))
        {
            return typeName;
        }

        var firstToken = new string(typeName.TakeWhile(static character => char.IsLetter(character)).ToArray());
        return firstToken is
            "bool" or "byte" or "sbyte" or "short" or "ushort" or "int" or "uint" or
            "long" or "ulong" or "char" or "float" or "double" or "decimal" or
            "string" or "object"
            ? typeName
            : $"global::{typeName}";
    }

    private static uint ComputeHash(string value)
    {
        var hash = 2166136261u;
        foreach (var character in value)
        {
            hash ^= character;
            hash *= 16777619;
        }

        return hash;
    }
}
