<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(AtomUICityDevelopTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AtomUI.City.Presentation/AtomUI.City.Presentation.csproj" />
    <Compile Include="../Shared/ProcessEntryPoint.cs" Link="ProcessEntryPoint.cs" />
  </ItemGroup>

</Project>
