using System.Text;
using AtomUI.City.Generators.Common;
using Microsoft.CodeAnalysis.CSharp;

namespace AtomUI.City.Generators.Localization;

internal static class LocalizationRegistrarSourceBuilder
{
    public static string Build(LocalizationManifest manifest)
    {
        if (manifest is null)
        {
            throw new ArgumentNullException(nameof(manifest));
        }

        var typeName = GeneratedCodeNames.CreateRegistrarTypeName(
            GeneratorFeature.Localization,
            "Manifest");
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.Append("namespace ").Append(typeName.Namespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("public static class ").Append(typeName.Name).AppendLine();
        builder.AppendLine("{");
        AppendStringList(builder, "SupportedCultures", manifest.SupportedCultures);
        AppendStringList(builder, "ResourceKeys", manifest.Resources.Select(resource => resource.Key).Distinct(StringComparer.Ordinal));
        AppendKeyConstants(builder, manifest.Resources);
        AppendPackageRegistration(builder, typeName.Name, manifest);
        builder.AppendLine("}");

        return builder.ToString().Replace("\r\n", "\n").Replace('\r', '\n');
    }

    private static void AppendStringList(
        StringBuilder builder,
        string propertyName,
        IEnumerable<string> values)
    {
        builder.Append("    public static global::System.Collections.Generic.IReadOnlyList<string> ")
            .Append(propertyName)
            .AppendLine(" { get; } =");
        builder.AppendLine("        global::System.Array.AsReadOnly(new string[]");
        builder.AppendLine("        {");
        foreach (var value in values.OrderBy(value => value, StringComparer.Ordinal))
        {
            builder.Append("            ").Append(ToStringLiteral(value)).AppendLine(",");
        }

        builder.AppendLine("        });");
        builder.AppendLine();
    }

    private static void AppendKeyConstants(
        StringBuilder builder,
        IEnumerable<LocalizedResourceManifestEntry> resources)
    {
        builder.AppendLine("    public static class Keys");
        builder.AppendLine("    {");
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var key in resources.Select(resource => resource.Key).Distinct(StringComparer.Ordinal).OrderBy(key => key, StringComparer.Ordinal))
        {
            var baseName = ToIdentifier(key);
            var name = baseName;
            var suffix = 2;
            while (!names.Add(name))
            {
                name = baseName + "_" + suffix++;
            }

            builder.Append("        public const string ").Append(name).Append(" = ")
                .Append(ToStringLiteral(key)).AppendLine(";");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendPackageRegistration(
        StringBuilder builder,
        string generatedTypeName,
        LocalizationManifest manifest)
    {
        builder.AppendLine("    public static void RegisterPackages(");
        builder.AppendLine("        global::AtomUI.City.Localization.LanguagePackageRegistry registry,");
        builder.AppendLine("        string ownerId)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(registry);");
        builder.AppendLine("        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(ownerId);");

        builder.AppendLine("        var result = registry.RegisterRange(");
        builder.AppendLine("            new global::AtomUI.City.Localization.LanguagePackageDescriptor[]");
        builder.AppendLine("            {");
        foreach (var package in manifest.Packages)
        {
            builder.AppendLine("                new global::AtomUI.City.Localization.LanguagePackageDescriptor(");
            builder.Append("                    ").Append(ToStringLiteral(package.PackageId)).AppendLine(",");
            builder.Append("                    global::System.Globalization.CultureInfo.GetCultureInfo(")
                .Append(ToStringLiteral(package.Culture)).AppendLine("),");
            builder.Append("                    global::AtomUI.City.Localization.ResourceScope.")
                .Append(package.Scope).AppendLine(")");
            builder.AppendLine("                {");
            builder.AppendLine("                    ProviderKind = global::AtomUI.City.Localization.LanguagePackageProviderKind.Assembly,");
            builder.Append("                    ScopeId = ").Append(ToStringLiteral(package.ScopeId)).AppendLine(",");
            builder.Append("                    LoadContext = global::System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(typeof(")
                .Append(generatedTypeName).AppendLine(").Assembly),");
            builder.Append("                    Location = typeof(").Append(generatedTypeName).AppendLine(").Assembly.Location,");
            builder.Append("                    ResourceBaseName = ").Append(ToStringLiteral(package.ResourceBaseName)).AppendLine(",");
            builder.Append("                    FallbackCulture = ").Append(ToCultureExpression(package.FallbackCulture)).AppendLine(",");
            builder.Append("                    Version = ").Append(ToStringLiteral(package.Version)).AppendLine(",");
            builder.Append("                    Checksum = ").Append(ToStringLiteral(package.Checksum)).AppendLine(",");
            builder.Append("                    ContributionId = ").Append(ToStringLiteral(package.ContributionId)).AppendLine(",");
            var criticalKeys = manifest.Resources
                .Where(resource => resource.Critical
                    && string.Equals(resource.PackageId, package.PackageId, StringComparison.Ordinal)
                    && string.Equals(resource.Culture, package.Culture, StringComparison.Ordinal))
                .Select(resource => resource.Key)
                .OrderBy(key => key, StringComparer.Ordinal)
                .ToArray();
            builder.Append("                    CriticalResourceKeys = ");
            AppendInlineStringArray(builder, criticalKeys);
            builder.AppendLine(",");
            builder.AppendLine("                },");
        }

        builder.AppendLine("            },");
        builder.AppendLine("            ownerId);");
        builder.AppendLine("        if (!result.Succeeded)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.InvalidOperationException(result.Error!.Message);");
        builder.AppendLine("        }");

        builder.AppendLine("    }");
    }

    private static string ToIdentifier(string key)
    {
        var builder = new StringBuilder(key.Length + 1);
        foreach (var character in key)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (builder.Length == 0 || char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        var identifier = builder.ToString();
        return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None
            ? identifier
            : "_" + identifier;
    }

    private static string ToCultureExpression(string? culture)
    {
        return culture is null
            ? "null"
            : "global::System.Globalization.CultureInfo.GetCultureInfo(" + ToStringLiteral(culture) + ")";
    }

    private static void AppendInlineStringArray(StringBuilder builder, IReadOnlyList<string> values)
    {
        builder.Append("new string[] { ");
        for (var index = 0; index < values.Count; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append(ToStringLiteral(values[index]));
        }

        builder.Append(" }");
    }

    private static string ToStringLiteral(string? value)
    {
        return value is null ? "null" : "@\"" + value.Replace("\"", "\"\"") + "\"";
    }
}
